export interface SP500Stock {
  ticker: string;
  name: string;
  subIndustry?: string;
}

export interface SP500Sector {
  id: string;
  name: string;
  icon: string;
  color: string;
  stocks: SP500Stock[];
}

export const SP500_SECTORS: SP500Sector[] = [
  {
    id: 'technology',
    name: 'Tecnología de la Información',
    icon: '💻',
    color: 'text-cyan-400 border-cyan-500/30 bg-cyan-500/10',
    stocks: [
      { ticker: 'AAPL', name: 'Apple Inc.', subIndustry: 'Electrónica de Consumo' },
      { ticker: 'MSFT', name: 'Microsoft Corporation', subIndustry: 'Software e Infraestructura' },
      { ticker: 'NVDA', name: 'NVIDIA Corporation', subIndustry: 'Semiconductores & IA' },
      { ticker: 'AVGO', name: 'Broadcom Inc.', subIndustry: 'Semiconductores' },
      { ticker: 'ORCL', name: 'Oracle Corporation', subIndustry: 'Software Cloud & Bases de Datos' },
      { ticker: 'CRM', name: 'Salesforce, Inc.', subIndustry: 'Software de Aplicaciones' },
      { ticker: 'ADBE', name: 'Adobe Inc.', subIndustry: 'Software de Diseño y Creación' },
      { ticker: 'AMD', name: 'Advanced Micro Devices', subIndustry: 'Semiconductores' },
      { ticker: 'QCOM', name: 'QUALCOMM Incorporated', subIndustry: 'Semiconductores Móviles' },
      { ticker: 'CSCO', name: 'Cisco Systems, Inc.', subIndustry: 'Equipos de Redes y Telecom' },
      { ticker: 'INTC', name: 'Intel Corporation', subIndustry: 'Semiconductores' },
      { ticker: 'TXN', name: 'Texas Instruments', subIndustry: 'Semiconductores Analógicos' },
      { ticker: 'IBM', name: 'International Business Machines', subIndustry: 'Servicios de TI & Cloud' },
      { ticker: 'NOW', name: 'ServiceNow, Inc.', subIndustry: 'Sistemas de Flujo de Trabajo' },
      { ticker: 'INTU', name: 'Intuit Inc.', subIndustry: 'Software Fiscal y Financiero' },
      { ticker: 'AMAT', name: 'Applied Materials, Inc.', subIndustry: 'Equipos de Semiconductores' },
      { ticker: 'MU', name: 'Micron Technology, Inc.', subIndustry: 'Memorias y Almacenamiento' },
      { ticker: 'LRCX', name: 'Lam Research Corporation', subIndustry: 'Equipos de Semiconductores' },
      { ticker: 'PANW', name: 'Palo Alto Networks', subIndustry: 'Ciberseguridad' },
      { ticker: 'KLAC', name: 'KLA Corporation', subIndustry: 'Equipos de Control de Procesos' },
      { ticker: 'SNPS', name: 'Synopsys, Inc.', subIndustry: 'Software EDA' },
      { ticker: 'CDNS', name: 'Cadence Design Systems', subIndustry: 'Software de Automatización' },
      { ticker: 'ADI', name: 'Analog Devices, Inc.', subIndustry: 'Semiconductores' },
      { ticker: 'NXPI', name: 'NXP Semiconductors N.V.', subIndustry: 'Automoción y Semiconductores' },
      { ticker: 'MCHP', name: 'Microchip Technology', subIndustry: 'Microcontroladores' },
      { ticker: 'FTNT', name: 'Fortinet, Inc.', subIndustry: 'Ciberseguridad' },
      { ticker: 'APH', name: 'Amphenol Corporation', subIndustry: 'Conectores Electrónicos' },
      { ticker: 'MSI', name: 'Motorola Solutions, Inc.', subIndustry: 'Comunicaciones Críticas' },
      { ticker: 'TEL', name: 'TE Connectivity Ltd.', subIndustry: 'Componentes Electrónicos' },
      { ticker: 'ANSS', name: 'ANSYS, Inc.', subIndustry: 'Software de Simulación' },
      { ticker: 'MPWR', name: 'Monolithic Power Systems', subIndustry: 'Circuitos de Potencia' },
      { ticker: 'ON', name: 'ON Semiconductor Corp.', subIndustry: 'Semiconductores de Potencia' },
      { ticker: 'HPE', name: 'Hewlett Packard Enterprise', subIndustry: 'Servidores & Infraestructura' },
      { ticker: 'KEYS', name: 'Keysight Technologies', subIndustry: 'Instrumentación Electrónica' },
      { ticker: 'STX', name: 'Seagate Technology Holdings', subIndustry: 'Almacenamiento de Datos' },
      { ticker: 'WDC', name: 'Western Digital Corporation', subIndustry: 'Discos Duros y Flash' },
      { ticker: 'GLW', name: 'Corning Incorporated', subIndustry: 'Vidrio Óptico Especial' },
      { ticker: 'ZBRA', name: 'Zebra Technologies Corp.', subIndustry: 'Captura Automática de Datos' },
      { ticker: 'IT', name: 'Gartner, Inc.', subIndustry: 'Investigación de TI' },
      { ticker: 'AKAM', name: 'Akamai Technologies, Inc.', subIndustry: 'Redes CDN y Ciberseguridad' },
      { ticker: 'GEN', name: 'Gen Digital Inc.', subIndustry: 'Software de Ciberseguridad' },
      { ticker: 'TRMB', name: 'Trimble Inc.', subIndustry: 'Sistemas GPS' },
      { ticker: 'SWKS', name: 'Skyworks Solutions, Inc.', subIndustry: 'Semiconductores de RF' },
      { ticker: 'QRVO', name: 'Qorvo, Inc.', subIndustry: 'Soluciones de Radiofrecuencia' },
      { ticker: 'FFIV', name: 'F5, Inc.', subIndustry: 'Seguridad de Redes' },
    ],
  },
  {
    id: 'health',
    name: 'Salud y Farmacia',
    icon: '🏥',
    color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
    stocks: [
      { ticker: 'LLY', name: 'Eli Lilly and Company', subIndustry: 'Farmacéutica & GLP-1' },
      { ticker: 'UNH', name: 'UnitedHealth Group Inc.', subIndustry: 'Seguros de Salud y Cuidados' },
      { ticker: 'JNJ', name: 'Johnson & Johnson', subIndustry: 'Farmacéutica y Tecnología Médica' },
      { ticker: 'ABBV', name: 'AbbVie Inc.', subIndustry: 'Biotecnología e Inmunología' },
      { ticker: 'MRK', name: 'Merck & Co., Inc.', subIndustry: 'Oncología y Vacunas' },
      { ticker: 'TMO', name: 'Thermo Fisher Scientific', subIndustry: 'Instrumentación Científica' },
      { ticker: 'ABT', name: 'Abbott Laboratories', subIndustry: 'Dispositivos Médicos y Diagnóstico' },
      { ticker: 'DHR', name: 'Danaher Corporation', subIndustry: 'Biotecnología y Diagnóstico' },
      { ticker: 'PFE', name: 'Pfizer Inc.', subIndustry: 'Farmacéutica y Vacunas' },
      { ticker: 'BMY', name: 'Bristol-Myers Squibb', subIndustry: 'Biofarmacéutica' },
      { ticker: 'AMGN', name: 'Amgen Inc.', subIndustry: 'Biotecnología' },
      { ticker: 'ISRG', name: 'Intuitive Surgical, Inc.', subIndustry: 'Robótica Quirúrgica da Vinci' },
      { ticker: 'SYK', name: 'Stryker Corporation', subIndustry: 'Equipos Ortopédicos y Médicos' },
      { ticker: 'ELV', name: 'Elevance Health, Inc.', subIndustry: 'Seguros Médicos' },
      { ticker: 'MDT', name: 'Medtronic plc', subIndustry: 'Tecnología y Dispositivos Médicos' },
      { ticker: 'GILD', name: 'Gilead Sciences, Inc.', subIndustry: 'Biotecnología y Antivirales' },
      { ticker: 'CVS', name: 'CVS Health Corporation', subIndustry: 'Farmacias y Servicios Sanitarios' },
      { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', subIndustry: 'Medicamentos Biotecnológicos' },
      { ticker: 'CI', name: 'The Cigna Group', subIndustry: 'Planes de Salud Globales' },
      { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', subIndustry: 'Fibrosis Quística y Terapia Génica' },
      { ticker: 'BDX', name: 'Becton, Dickinson and Company', subIndustry: 'Suministros Médicos' },
      { ticker: 'ZTS', name: 'Zoetis Inc.', subIndustry: 'Salud Animal' },
      { ticker: 'HCA', name: 'HCA Healthcare, Inc.', subIndustry: 'Operador de Hospitales' },
      { ticker: 'BSX', name: 'Boston Scientific Corp.', subIndustry: 'Dispositivos Intervencionistas' },
      { ticker: 'MCK', name: 'McKesson Corporation', subIndustry: 'Distribución Farmacéutica' },
      { ticker: 'HUM', name: 'Humana Inc.', subIndustry: 'Seguros Médicos Medicare' },
      { ticker: 'EW', name: 'Edwards Lifesciences', subIndustry: 'Válvulas Cardíacas Estructurales' },
      { ticker: 'IDXX', name: 'IDEXX Laboratories, Inc.', subIndustry: 'Diagnóstico Veterinario' },
      { ticker: 'COR', name: 'Cencora, Inc.', subIndustry: 'Distribución Mayorista Sanitaria' },
      { ticker: 'DXCM', name: 'DexCom, Inc.', subIndustry: 'Monitorización de Glucosa' },
      { ticker: 'IQV', name: 'IQVIA Holdings Inc.', subIndustry: 'Ensayos Clínicos e Inteligencia' },
      { ticker: 'A', name: 'Agilent Technologies, Inc.', subIndustry: 'Ciencias de la Vida y Diagnóstico' },
      { ticker: 'MTD', name: 'Mettler-Toledo International', subIndustry: 'Básculas e Instrumentos de Laboratorio' },
      { ticker: 'RMD', name: 'ResMed Inc.', subIndustry: 'Tratamiento del Sueño y Respiratorio' },
      { ticker: 'ALGN', name: 'Align Technology, Inc.', subIndustry: 'Ortodoncia Invisible (Invisalign)' },
      { ticker: 'BAX', name: 'Baxter International Inc.', subIndustry: 'Terapia Renal y Hospitalaria' },
      { ticker: 'STE', name: 'STERIS plc', subIndustry: 'Esterilización y Quirófanos' },
      { ticker: 'HOLX', name: 'Hologic, Inc.', subIndustry: 'Diagnóstico y Salud Femenina' },
    ],
  },
  {
    id: 'financials',
    name: 'Finanzas y Banca',
    icon: '🏦',
    color: 'text-amber-400 border-amber-500/30 bg-amber-500/10',
    stocks: [
      { ticker: 'BRK-B', name: 'Berkshire Hathaway Inc.', subIndustry: 'Conglomerado & Seguros (Buffett)' },
      { ticker: 'JPM', name: 'JPMorgan Chase & Co.', subIndustry: 'Banca Universal e Inversión' },
      { ticker: 'V', name: 'Visa Inc.', subIndustry: 'Redes Globales de Pago' },
      { ticker: 'MA', name: 'Mastercard Incorporated', subIndustry: 'Redes Globales de Pago' },
      { ticker: 'BAC', name: 'Bank of America Corp.', subIndustry: 'Banca Comercial y Patrimonial' },
      { ticker: 'WFC', name: 'Wells Fargo & Company', subIndustry: 'Banca Minorista y Préstamos' },
      { ticker: 'MS', name: 'Morgan Stanley', subIndustry: 'Banca de Inversión y Gestión' },
      { ticker: 'GS', name: 'The Goldman Sachs Group', subIndustry: 'Banca de Inversión y Trading' },
      { ticker: 'BLK', name: 'BlackRock, Inc.', subIndustry: 'Gestora de Activos & ETFs (iShares)' },
      { ticker: 'C', name: 'Citigroup Inc.', subIndustry: 'Banca Global Corporativa' },
      { ticker: 'AXP', name: 'American Express Company', subIndustry: 'Tarjetas de Crédito y Servicios' },
      { ticker: 'SCHW', name: 'The Charles Schwab Corp.', subIndustry: 'Brokerage y Gestión Patrimonial' },
      { ticker: 'CB', name: 'Chubb Limited', subIndustry: 'Seguros Patrimoniales y Comerciales' },
      { ticker: 'MMC', name: 'Marsh & McLennan Companies', subIndustry: 'Bróker de Seguros y Riesgos' },
      { ticker: 'PGR', name: 'The Progressive Corporation', subIndustry: 'Seguros de Automóvil y Hogar' },
      { ticker: 'AON', name: 'Aon plc', subIndustry: 'Consultoría y Bróker de Seguros' },
      { ticker: 'CME', name: 'CME Group Inc.', subIndustry: 'Bolsas de Derivados y Futuros' },
      { ticker: 'ICE', name: 'Intercontinental Exchange', subIndustry: 'Bolsas (NYSE) y Mercados' },
      { ticker: 'USB', name: 'U.S. Bancorp', subIndustry: 'Banca Regional Líder' },
      { ticker: 'PNC', name: 'The PNC Financial Services', subIndustry: 'Banca Comercial y Corporativa' },
      { ticker: 'MCO', name: 'Moody\'s Corporation', subIndustry: 'Calificación Crediticia y Rating' },
      { ticker: 'TRV', name: 'The Travelers Companies', subIndustry: 'Seguros de Daños y Accidentes' },
      { ticker: 'AIG', name: 'American International Group', subIndustry: 'Seguros Globales' },
      { ticker: 'MET', name: 'MetLife, Inc.', subIndustry: 'Seguros de Vida y Rentas' },
      { ticker: 'PRU', name: 'Prudential Financial, Inc.', subIndustry: 'Seguros y Gestión de Pensiones' },
      { ticker: 'AFL', name: 'Aflac Incorporated', subIndustry: 'Seguros de Salud Suplementarios' },
      { ticker: 'ALL', name: 'The Allstate Corporation', subIndustry: 'Seguros de Automóvil' },
      { ticker: 'BK', name: 'The Bank of New York Mellon', subIndustry: 'Custodia de Activos Globales' },
      { ticker: 'STT', name: 'State Street Corporation', subIndustry: 'Custodia y ETFs (SPDR)' },
      { ticker: 'COF', name: 'Capital One Financial Corp.', subIndustry: 'Tarjetas de Crédito y Financiación' },
      { ticker: 'TFC', name: 'Truist Financial Corporation', subIndustry: 'Banca Regional' },
      { ticker: 'FITB', name: 'Fifth Third Bancorp', subIndustry: 'Banca Comercial Regional' },
      { ticker: 'MTB', name: 'M&T Bank Corporation', subIndustry: 'Banca Regional del Este' },
      { ticker: 'DFS', name: 'Discover Financial Services', subIndustry: 'Tarjetas de Crédito y Préstamos' },
      { ticker: 'HBAN', name: 'Huntington Bancshares', subIndustry: 'Banca Regional del Medio Oeste' },
      { ticker: 'KEY', name: 'KeyCorp', subIndustry: 'Banca Minorista y Corporativa' },
      { ticker: 'CINF', name: 'Cincinnati Financial Corp.', subIndustry: 'Seguros Patrimoniales' },
      { ticker: 'HIG', name: 'The Hartford Financial', subIndustry: 'Seguros Comerciales y de Vida' },
    ],
  },
  {
    id: 'consumer_disc',
    name: 'Consumo Discrecional',
    icon: '🛒',
    color: 'text-violet-400 border-violet-500/30 bg-violet-500/10',
    stocks: [
      { ticker: 'AMZN', name: 'Amazon.com, Inc.', subIndustry: 'Comercio Electrónico & AWS Cloud' },
      { ticker: 'TSLA', name: 'Tesla, Inc.', subIndustry: 'Vehículos Eléctricos y Energía' },
      { ticker: 'HD', name: 'The Home Depot, Inc.', subIndustry: 'Mejoras del Hogar y Bricolaje' },
      { ticker: 'MCD', name: 'McDonald\'s Corporation', subIndustry: 'Restauración Rápida Global' },
      { ticker: 'NKE', name: 'NIKE, Inc.', subIndustry: 'Calzado y Ropa Deportiva' },
      { ticker: 'LOW', name: 'Lowe\'s Companies, Inc.', subIndustry: 'Bricolaje y Construcción' },
      { ticker: 'SBUX', name: 'Starbucks Corporation', subIndustry: 'Cafeterías y Bebidas de Marca' },
      { ticker: 'BKNG', name: 'Booking Holdings Inc.', subIndustry: 'Viajes Online y Alojamientos' },
      { ticker: 'TJX', name: 'The TJX Companies, Inc.', subIndustry: 'Ropa y Hogar con Descuento' },
      { ticker: 'MAR', name: 'Marriott International', subIndustry: 'Cadenas Hoteleras' },
      { ticker: 'CMG', name: 'Chipotle Mexican Grill', subIndustry: 'Restauración Fast-Casual' },
      { ticker: 'ORLY', name: 'O\'Reilly Automotive, Inc.', subIndustry: 'Recambios de Automóviles' },
      { ticker: 'AZO', name: 'AutoZone, Inc.', subIndustry: 'Repuestos y Accesorios de Coches' },
      { ticker: 'ROST', name: 'Ross Stores, Inc.', subIndustry: 'Grandes Almacenes de Descuento' },
      { ticker: 'DHI', name: 'D.R. Horton, Inc.', subIndustry: 'Construcción de Viviendas' },
      { ticker: 'LEN', name: 'Lennar Corporation', subIndustry: 'Promoción Inmobiliaria Residencial' },
      { ticker: 'ABNB', name: 'Airbnb, Inc.', subIndustry: 'Alquiler Vacacional y Alojamientos' },
      { ticker: 'YUM', name: 'Yum! Brands, Inc.', subIndustry: 'Franquicias (KFC, Pizza Hut, Taco Bell)' },
      { ticker: 'GM', name: 'General Motors Company', subIndustry: 'Fabricación de Automóviles' },
      { ticker: 'F', name: 'Ford Motor Company', subIndustry: 'Automoción y Camionetas' },
      { ticker: 'HLT', name: 'Hilton Worldwide Holdings', subIndustry: 'Hoteles y Resorts' },
      { ticker: 'RCL', name: 'Royal Caribbean Cruises', subIndustry: 'Cruceros de Vacaciones' },
      { ticker: 'CCL', name: 'Carnival Corporation', subIndustry: 'Líneas de Cruceros' },
      { ticker: 'LVS', name: 'Las Vegas Sands Corp.', subIndustry: 'Casinos y Complejos Turísticos' },
      { ticker: 'EBAY', name: 'eBay Inc.', subIndustry: 'Subastas y Marketplace Online' },
      { ticker: 'ULTA', name: 'Ulta Beauty, Inc.', subIndustry: 'Cosméticos y Salones de Belleza' },
      { ticker: 'TSCO', name: 'Tractor Supply Company', subIndustry: 'Estilo de Vida Rural y Agricultura' },
      { ticker: 'DRI', name: 'Darden Restaurants, Inc.', subIndustry: 'Cadenas de Restaurantes (Olive Garden)' },
      { ticker: 'GPC', name: 'Genuine Parts Company', subIndustry: 'Distribución de Repuestos (NAPA)' },
      { ticker: 'BBY', name: 'Best Buy Co., Inc.', subIndustry: 'Minorista de Electrónica' },
      { ticker: 'EXPE', name: 'Expedia Group, Inc.', subIndustry: 'Agencias de Viajes Online' },
      { ticker: 'RL', name: 'Ralph Lauren Corporation', subIndustry: 'Moda y Lujo Premium' },
      { ticker: 'MGM', name: 'MGM Resorts International', subIndustry: 'Casinos y Espectáculos' },
      { ticker: 'WYNN', name: 'Wynn Resorts, Limited', subIndustry: 'Hoteles Casino de Gran Lujo' },
      { ticker: 'NCLH', name: 'Norwegian Cruise Line', subIndustry: 'Operador de Cruceros' },
    ],
  },
  {
    id: 'communication',
    name: 'Servicios de Comunicación',
    icon: '📱',
    color: 'text-indigo-400 border-indigo-500/30 bg-indigo-500/10',
    stocks: [
      { ticker: 'GOOGL', name: 'Alphabet Inc. (Clase A)', subIndustry: 'Motores de Búsqueda, Cloud & YouTube' },
      { ticker: 'GOOG', name: 'Alphabet Inc. (Clase C)', subIndustry: 'Publicidad Digital e IA' },
      { ticker: 'META', name: 'Meta Platforms, Inc.', subIndustry: 'Redes Sociales (FB, Insta, WhatsApp)' },
      { ticker: 'NFLX', name: 'Netflix, Inc.', subIndustry: 'Streaming Global de Vídeo' },
      { ticker: 'DIS', name: 'The Walt Disney Company', subIndustry: 'Entretenimiento, Parques y Cine' },
      { ticker: 'CMCSA', name: 'Comcast Corporation', subIndustry: 'Cable, Banda Ancha & Universal Studios' },
      { ticker: 'T', name: 'AT&T Inc.', subIndustry: 'Telecomunicaciones y 5G' },
      { ticker: 'VZ', name: 'Verizon Communications', subIndustry: 'Redes Móviles e Internet Fibra' },
      { ticker: 'TMUS', name: 'T-Mobile US, Inc.', subIndustry: 'Telefonía Móvil 5G' },
      { ticker: 'CHTR', name: 'Charter Communications', subIndustry: 'Servicios de Cable e Internet' },
      { ticker: 'EA', name: 'Electronic Arts Inc.', subIndustry: 'Videojuegos (EA Sports, FIFA/FC)' },
      { ticker: 'WBD', name: 'Warner Bros. Discovery', subIndustry: 'Contenidos Cinematográficos y TV' },
      { ticker: 'TTWO', name: 'Take-Two Interactive', subIndustry: 'Videojuegos (GTA, Rockstar, 2K)' },
      { ticker: 'OMC', name: 'Omnicom Group Inc.', subIndustry: 'Publicidad y Marketing Global' },
      { ticker: 'LYV', name: 'Live Nation Entertainment', subIndustry: 'Conciertos y Venta de Entradas' },
      { ticker: 'IPG', name: 'The Interpublic Group', subIndustry: 'Agencias de Medios y RRPP' },
      { ticker: 'FOXA', name: 'Fox Corporation (Clase A)', subIndustry: 'Televisión y Noticias' },
      { ticker: 'NWSA', name: 'News Corporation', subIndustry: 'Prensa (The Wall Street Journal)' },
      { ticker: 'MTCH', name: 'Match Group, Inc.', subIndustry: 'Citas Online (Tinder, Hinge)' },
    ],
  },
  {
    id: 'industrials',
    name: 'Industria y Aeroespacial',
    icon: '🏭',
    color: 'text-orange-400 border-orange-500/30 bg-orange-500/10',
    stocks: [
      { ticker: 'GE', name: 'General Electric Company', subIndustry: 'Turbinas de Aviación y Energía' },
      { ticker: 'CAT', name: 'Caterpillar Inc.', subIndustry: 'Maquinaria Pesada y Minería' },
      { ticker: 'UNP', name: 'Union Pacific Corporation', subIndustry: 'Transporte Ferroviario de Mercancías' },
      { ticker: 'HON', name: 'Honeywell International', subIndustry: 'Automatización y Aeroespacio' },
      { ticker: 'RTX', name: 'RTX Corporation (Raytheon)', subIndustry: 'Defensa, Radares y Motores Pratt' },
      { ticker: 'BA', name: 'The Boeing Company', subIndustry: 'Aviones Comerciales y Espacio' },
      { ticker: 'DE', name: 'Deere & Company', subIndustry: 'Maquinaria Agrícola (John Deere)' },
      { ticker: 'LMT', name: 'Lockheed Martin Corp.', subIndustry: 'Cazas Militares (F-35) y Misiles' },
      { ticker: 'UPS', name: 'United Parcel Service', subIndustry: 'Logística y Envíos de Paquetería' },
      { ticker: 'ADP', name: 'Automatic Data Processing', subIndustry: 'Servicios de Nóminas y RRHH' },
      { ticker: 'ETN', name: 'Eaton Corporation plc', subIndustry: 'Sistemas de Gestión Eléctrica' },
      { ticker: 'WM', name: 'Waste Management, Inc.', subIndustry: 'Gestión y Reciclaje de Residuos' },
      { ticker: 'ITW', name: 'Illinois Tool Works Inc.', subIndustry: 'Equipamiento Industrial Diverso' },
      { ticker: 'EMR', name: 'Emerson Electric Co.', subIndustry: 'Automatización de Procesos Industriales' },
      { ticker: 'PH', name: 'Parker-Hannifin Corp.', subIndustry: 'Tecnologías de Control de Movimiento' },
      { ticker: 'GD', name: 'General Dynamics Corp.', subIndustry: 'Submarinos Nucleares y Aviación Gulfstream' },
      { ticker: 'FDX', name: 'FedEx Corporation', subIndustry: 'Transporte Aéreo y Terrestre Exprés' },
      { ticker: 'NOC', name: 'Northrop Grumman Corp.', subIndustry: 'Bombarderos Estratégicos (B-21)' },
      { ticker: 'CSX', name: 'CSX Corporation', subIndustry: 'Transporte por Ferrocarril' },
      { ticker: 'NSC', name: 'Norfolk Southern Corp.', subIndustry: 'Redes Ferroviarias' },
      { ticker: 'PCAR', name: 'PACCAR Inc', subIndustry: 'Camiones Pesados (Kenworth, Peterbilt)' },
      { ticker: 'TDG', name: 'TransDigm Group Inc.', subIndustry: 'Componentes Críticos para Aeronaves' },
      { ticker: 'CMI', name: 'Cummins Inc.', subIndustry: 'Motores Diésel y Soluciones de Gas' },
      { ticker: 'ROK', name: 'Rockwell Automation, Inc.', subIndustry: 'Automatización y Software Industrial' },
      { ticker: 'CTAS', name: 'Cintas Corporation', subIndustry: 'Uniformes y Suministros de Empresa' },
      { ticker: 'GWW', name: 'W.W. Grainger, Inc.', subIndustry: 'Suministros de Mantenimiento (MRO)' },
      { ticker: 'FAST', name: 'Fastenal Company', subIndustry: 'Fijaciones y Suministros Industriales' },
      { ticker: 'CARR', name: 'Carrier Global Corporation', subIndustry: 'Aire Acondicionado y Climatización' },
      { ticker: 'OTIS', name: 'Otis Worldwide Corporation', subIndustry: 'Ascensores y Escaleras Mecánicas' },
      { ticker: 'TT', name: 'Trane Technologies plc', subIndustry: 'Control de Clima Comercial' },
      { ticker: 'VMC', name: 'Vulcan Materials Company', subIndustry: 'Áridos y Materiales de Construcción' },
      { ticker: 'URI', name: 'United Rentals, Inc.', subIndustry: 'Alquiler de Maquinaria Pesada' },
      { ticker: 'XYL', name: 'Xylem Inc.', subIndustry: 'Tecnología del Agua y Tratamiento' },
      { ticker: 'LHX', name: 'L3Harris Technologies', subIndustry: 'Sistemas Tácticos y Comunicaciones' },
      { ticker: 'EXPD', name: 'Expeditors International', subIndustry: 'Logística de Carga Global' },
      { ticker: 'JBHT', name: 'J.B. Hunt Transport Services', subIndustry: 'Transporte en Camión e Intermodal' },
    ],
  },
  {
    id: 'consumer_staples',
    name: 'Consumo Básico',
    icon: '🥫',
    color: 'text-yellow-400 border-yellow-500/30 bg-yellow-500/10',
    stocks: [
      { ticker: 'PG', name: 'The Procter & Gamble Co.', subIndustry: 'Cuidado del Hogar (Gillette, Pampers, Ariel)' },
      { ticker: 'COST', name: 'Costco Wholesale Corp.', subIndustry: 'Clubes de Compra por Membresía' },
      { ticker: 'WMT', name: 'Walmart Inc.', subIndustry: 'Hipermercados y Gran Distribución' },
      { ticker: 'KO', name: 'The Coca-Cola Company', subIndustry: 'Refrescos y Bebidas No Alcohólicas' },
      { ticker: 'PEP', name: 'PepsiCo, Inc.', subIndustry: 'Snacks (Lay\'s, Doritos) y Refrescos' },
      { ticker: 'PM', name: 'Philip Morris International', subIndustry: 'Tabaco y Productos Libres de Humo (IQOS)' },
      { ticker: 'MDLZ', name: 'Mondelez International', subIndustry: 'Chocolates y Galletas (Oreo, Milka)' },
      { ticker: 'MO', name: 'Altria Group, Inc.', subIndustry: 'Tabaco y Derivados (Marlboro EE.UU.)' },
      { ticker: 'CL', name: 'Colgate-Palmolive Company', subIndustry: 'Higiene Bucal y Cuidado Personal' },
      { ticker: 'TGT', name: 'Target Corporation', subIndustry: 'Grandes Superficies Minoristas' },
      { ticker: 'KMB', name: 'Kimberly-Clark Corporation', subIndustry: 'Pañuelos y Papel Tisú (Kleenex, Huggies)' },
      { ticker: 'STZ', name: 'Constellation Brands, Inc.', subIndustry: 'Cervezas (Corona EE.UU., Modelo) y Vinos' },
      { ticker: 'MNST', name: 'Monster Beverage Corp.', subIndustry: 'Bebidas Energéticas' },
      { ticker: 'GIS', name: 'General Mills, Inc.', subIndustry: 'Cereales y Alimentos (Cheerios, Old El Paso)' },
      { ticker: 'ADM', name: 'Archer-Daniels-Midland', subIndustry: 'Procesamiento de Granos Agrícolas' },
      { ticker: 'SYY', name: 'Sysco Corporation', subIndustry: 'Distribución de Alimentos a Hostelería' },
      { ticker: 'HSY', name: 'The Hershey Company', subIndustry: 'Chocolates y Golosinas' },
      { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.', subIndustry: 'Café monodosis y Refrescos' },
      { ticker: 'K', name: 'Kellanova (Kellogg)', subIndustry: 'Snacks y Aperitivos (Pringles)' },
      { ticker: 'MKC', name: 'McCormick & Company', subIndustry: 'Especias y Condimentos' },
      { ticker: 'EL', name: 'The Estée Lauder Companies', subIndustry: 'Cosméticos de Lujo y Perfumería' },
      { ticker: 'CLX', name: 'The Clorox Company', subIndustry: 'Productos de Desinfección y Limpieza' },
      { ticker: 'CAG', name: 'Conagra Brands, Inc.', subIndustry: 'Comidas Congeladas y Envasadas' },
      { ticker: 'HRL', name: 'Hormel Foods Corporation', subIndustry: 'Carnes Procesadas y Alimentos' },
      { ticker: 'TAP', name: 'Molson Coors Beverage Co.', subIndustry: 'Cervecería' },
      { ticker: 'CHD', name: 'Church & Dwight Co., Inc.', subIndustry: 'Bicarbonato Arm & Hammer y Limpieza' },
      { ticker: 'CPB', name: 'The Campbell\'s Company', subIndustry: 'Sopas y Caldos Preparados' },
    ],
  },
  {
    id: 'energy',
    name: 'Energía y Petróleo',
    icon: '⚡',
    color: 'text-red-400 border-red-500/30 bg-red-500/10',
    stocks: [
      { ticker: 'XOM', name: 'Exxon Mobil Corporation', subIndustry: 'Petróleo y Gas Integrado Global' },
      { ticker: 'CVX', name: 'Chevron Corporation', subIndustry: 'Exploración, Refino y Gas Natural' },
      { ticker: 'COP', name: 'ConocoPhillips', subIndustry: 'Exploración y Producción (Upstream)' },
      { ticker: 'EOG', name: 'EOG Resources, Inc.', subIndustry: 'Petróleo de Esquisto (Shale Oil)' },
      { ticker: 'SLB', name: 'Schlumberger Limited', subIndustry: 'Servicios y Tecnología para Pozos' },
      { ticker: 'MPC', name: 'Marathon Petroleum Corp.', subIndustry: 'Refino y Gasolineras' },
      { ticker: 'PSX', name: 'Phillips 66', subIndustry: 'Refino de Combustibles y Químicos' },
      { ticker: 'VLO', name: 'Valero Energy Corporation', subIndustry: 'Refino y Producción de Etanol' },
      { ticker: 'OXY', name: 'Occidental Petroleum Corp.', subIndustry: 'Producción en Cuenca Pérmica' },
      { ticker: 'WMB', name: 'The Williams Companies', subIndustry: 'Oleoductos y Gasoductos' },
      { ticker: 'KMI', name: 'Kinder Morgan, Inc.', subIndustry: 'Infraestructura Energética Midstream' },
      { ticker: 'HES', name: 'Hess Corporation', subIndustry: 'Proyectos Petrolíferos en Guyana' },
      { ticker: 'BKR', name: 'Baker Hughes Company', subIndustry: 'Equipos y Servicios para Energía' },
      { ticker: 'HAL', name: 'Halliburton Company', subIndustry: 'Fracturación Hidráulica y Perforación' },
      { ticker: 'FANG', name: 'Diamondback Energy, Inc.', subIndustry: 'Extracción de Hidrocarburos' },
      { ticker: 'DVN', name: 'Devon Energy Corporation', subIndustry: 'Petróleo y Gas No Convencional' },
      { ticker: 'TRGP', name: 'Targa Resources Corp.', subIndustry: 'Líquidos de Gas Natural (LGN)' },
      { ticker: 'CTRA', name: 'Coterra Energy Inc.', subIndustry: 'Gas Natural en Marcellus' },
      { ticker: 'MRO', name: 'Marathon Oil Corporation', subIndustry: 'Petróleo y Gas en EE.UU.' },
      { ticker: 'EQT', name: 'EQT Corporation', subIndustry: 'Mayor Productor de Gas Natural de EE.UU.' },
      { ticker: 'OKE', name: 'ONEOK, Inc.', subIndustry: 'Sistemas Midstream de Gas Natural' },
      { ticker: 'APA', name: 'APA Corporation (Apache)', subIndustry: 'Exploración Internacional' },
    ],
  },
  {
    id: 'materials',
    name: 'Materiales Básicos',
    icon: '⛏️',
    color: 'text-teal-400 border-teal-500/30 bg-teal-500/10',
    stocks: [
      { ticker: 'LIN', name: 'Linde plc', subIndustry: 'Gases Industriales y Médicos' },
      { ticker: 'SHW', name: 'The Sherwin-Williams Co.', subIndustry: 'Pinturas y Recubrimientos' },
      { ticker: 'APD', name: 'Air Products and Chemicals', subIndustry: 'Hidrógeno y Gases Industriales' },
      { ticker: 'ECL', name: 'Ecolab Inc.', subIndustry: 'Tratamiento de Aguas y Desinfección' },
      { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', subIndustry: 'Minería de Cobre y Oro' },
      { ticker: 'NEM', name: 'Newmont Corporation', subIndustry: 'Mayor Minera de Oro del Mundo' },
      { ticker: 'CTVA', name: 'Corteva, Inc.', subIndustry: 'Semillas y Protección de Cultivos' },
      { ticker: 'DOW', name: 'Dow Inc.', subIndustry: 'Polímeros y Productos Químicos' },
      { ticker: 'DD', name: 'DuPont de Nemours, Inc.', subIndustry: 'Materiales Avanzados para Electrónica' },
      { ticker: 'PPG', name: 'PPG Industries, Inc.', subIndustry: 'Pinturas para Automoción y Aeroespacio' },
      { ticker: 'NUC', name: 'Nucor Corporation', subIndustry: 'Producción de Acero Reciclado' },
      { ticker: 'ALB', name: 'Albemarle Corporation', subIndustry: 'Litio para Baterías Eléctricas' },
      { ticker: 'MLM', name: 'Martin Marietta Materials', subIndustry: 'Gravas, Cemento y Hormigón' },
      { ticker: 'CE', name: 'Celanese Corporation', subIndustry: 'Materiales Químicos Especiales' },
      { ticker: 'EMN', name: 'Eastman Chemical Company', subIndustry: 'Fibras y Plásticos Técnicos' },
      { ticker: 'IFF', name: 'International Flavors & Fragrances', subIndustry: 'Aromas y Fragancias' },
      { ticker: 'BALL', name: 'Ball Corporation', subIndustry: 'Latas de Aluminio para Bebidas' },
      { ticker: 'IP', name: 'International Paper Company', subIndustry: 'Embalajes de Cartón Ondulado' },
      { ticker: 'PKG', name: 'Packaging Corporation of America', subIndustry: 'Cajas de Cartón y Envases' },
      { ticker: 'CF', name: 'CF Industries Holdings, Inc.', subIndustry: 'Fertilizantes Nitrogenados' },
      { ticker: 'MOS', name: 'The Mosaic Company', subIndustry: 'Fosfatos y Potasa Agrícola' },
      { ticker: 'FMC', name: 'FMC Corporation', subIndustry: 'Insecticidas y Herbicidas Agrícolas' },
    ],
  },
  {
    id: 'utilities',
    name: 'Servicios Públicos (Utilities)',
    icon: '💡',
    color: 'text-lime-400 border-lime-500/30 bg-lime-500/10',
    stocks: [
      { ticker: 'NEE', name: 'NextEra Energy, Inc.', subIndustry: 'Líder en Energía Eólica y Solar' },
      { ticker: 'SO', name: 'The Southern Company', subIndustry: 'Generación y Distribución Eléctrica' },
      { ticker: 'DUK', name: 'Duke Energy Corporation', subIndustry: 'Redes Eléctricas y Centrales de Gas' },
      { ticker: 'CEG', name: 'Constellation Energy Corp.', subIndustry: 'Mayor Productor Nuclear de EE.UU.' },
      { ticker: 'SRE', name: 'Sempra', subIndustry: 'Infraestructura de Gas Natural Licuado (GNL)' },
      { ticker: 'AEP', name: 'American Electric Power', subIndustry: 'Transmisión de Alta Tensión' },
      { ticker: 'D', name: 'Dominion Energy, Inc.', subIndustry: 'Suministro Eléctrico en Virginia y Carolinas' },
      { ticker: 'PEG', name: 'Public Service Enterprise', subIndustry: 'Electricidad y Gas en Nueva Jersey' },
      { ticker: 'EXC', name: 'Exelon Corporation', subIndustry: 'Distribuidora Eléctrica Urbana' },
      { ticker: 'ED', name: 'Consolidated Edison, Inc.', subIndustry: 'Luz y Vapor en Nueva York' },
      { ticker: 'XEL', name: 'Xcel Energy Inc.', subIndustry: 'Transición a Energía Renovable' },
      { ticker: 'PCG', name: 'PG&E Corporation', subIndustry: 'Electricidad y Gas en California' },
      { ticker: 'WEC', name: 'WEC Energy Group, Inc.', subIndustry: 'Servicios Públicos en el Medio Oeste' },
      { ticker: 'ETR', name: 'Entergy Corporation', subIndustry: 'Electricidad y Centrales Nucleares del Sur' },
      { ticker: 'ES', name: 'Eversource Energy', subIndustry: 'Redes Eléctricas en Nueva Inglaterra' },
      { ticker: 'FE', name: 'FirstEnergy Corp.', subIndustry: 'Distribución en Ohio y Pensilvania' },
      { ticker: 'AEE', name: 'Ameren Corporation', subIndustry: 'Energía en Misuri e Illinois' },
      { ticker: 'PPL', name: 'PPL Corporation', subIndustry: 'Redes Eléctricas Reguladas' },
      { ticker: 'CMS', name: 'CMS Energy Corporation', subIndustry: 'Electricidad y Gas en Míchigan' },
      { ticker: 'DTE', name: 'DTE Energy Company', subIndustry: 'Suministro Eléctrico en Detroit' },
      { ticker: 'CNP', name: 'CenterPoint Energy, Inc.', subIndustry: 'Infraestructura de Transmisión en Texas' },
      { ticker: 'NI', name: 'NiSource Inc.', subIndustry: 'Distribución de Gas Natural' },
      { ticker: 'ATO', name: 'Atmos Energy Corporation', subIndustry: 'Mayor Distribuidor de Gas Natural Exclusivo' },
      { ticker: 'NRG', name: 'NRG Energy, Inc.', subIndustry: 'Comercializadora Minorista de Electricidad' },
    ],
  },
  {
    id: 'real_estate',
    name: 'Inmobiliario y SOCIMIs (REITs)',
    icon: '🏢',
    color: 'text-pink-400 border-pink-500/30 bg-pink-500/10',
    stocks: [
      { ticker: 'PLD', name: 'Prologis, Inc.', subIndustry: 'Naves Logísticas para E-commerce' },
      { ticker: 'AMT', name: 'American Tower Corp.', subIndustry: 'Torres de Telecomunicaciones Móviles' },
      { ticker: 'EQIX', name: 'Equinix, Inc.', subIndustry: 'Centros de Datos y Conectividad Cloud' },
      { ticker: 'CCI', name: 'Crown Castle Inc.', subIndustry: 'Torres Móviles y Fibra Óptica' },
      { ticker: 'PSA', name: 'Public Storage', subIndustry: 'Almacenes de Autoalmacenaje (Trasteros)' },
      { ticker: 'O', name: 'Realty Income Corporation', subIndustry: 'Inmuebles Comerciales con Dividendo Mensual' },
      { ticker: 'DLR', name: 'Digital Realty Trust', subIndustry: 'Data Centers de Gran Escala' },
      { ticker: 'SPG', name: 'Simon Property Group, Inc.', subIndustry: 'Centros Comerciales y Outlets Premium' },
      { ticker: 'WELL', name: 'Welltower Inc.', subIndustry: 'Residencias de Mayores e Inmuebles Médicos' },
      { ticker: 'SBAC', name: 'SBA Communications Corp.', subIndustry: 'Torres Celulares Inalámbricas' },
      { ticker: 'VICI', name: 'VICI Properties Inc.', subIndustry: 'Propiedades de Casinos y Ocio (Las Vegas)' },
      { ticker: 'AVB', name: 'AvalonBay Communities', subIndustry: 'Edificios Residenciales de Apartamentos' },
      { ticker: 'EQR', name: 'Equity Residential', subIndustry: 'Apartamentos Urbanos de Lujo' },
      { ticker: 'WY', name: 'Weyerhaeuser Company', subIndustry: 'Bosques Madereros y Gestión Forestal' },
      { ticker: 'ARE', name: 'Alexandria Real Estate', subIndustry: 'Laboratorios de Ciencias de la Vida' },
      { ticker: 'EXR', name: 'Extra Space Storage Inc.', subIndustry: 'Trasteros y Almacenaje Personal' },
      { ticker: 'MAA', name: 'Mid-America Apartment', subIndustry: 'Comunidades de Pisos en el Sunbelt' },
      { ticker: 'INVH', name: 'Invitation Homes Inc.', subIndustry: 'Alquiler de Casas Unifamiliares' },
      { ticker: 'ESS', name: 'Essex Property Trust, Inc.', subIndustry: 'Viviendas en la Costa Oeste' },
      { ticker: 'CPT', name: 'Camden Property Trust', subIndustry: 'Complejos de Apartamentos' },
      { ticker: 'UDR', name: 'UDR, Inc.', subIndustry: 'Apartamentos Multifamiliares' },
      { ticker: 'KIM', name: 'Kimco Realty Corporation', subIndustry: 'Supermercados en Parques Comerciales' },
      { ticker: 'REG', name: 'Regency Centers Corp.', subIndustry: 'Centros Comerciales de Conveniencia' },
      { ticker: 'HST', name: 'Host Hotels & Resorts', subIndustry: 'Hoteles de Lujo y Resorts' },
      { ticker: 'BXP', name: 'BXP, Inc. (Boston Properties)', subIndustry: 'Torres de Oficinas Clase A' },
      { ticker: 'FRT', name: 'Federal Realty Investment', subIndustry: 'Zonas Comerciales Mixtas de Alto Poder' },
    ],
  },
];

