'use client';
import { useState } from 'react';
import Link from 'next/link';
import { references, topologies, type Topology } from '@/data/ai-journey';
import { NetworkDiagram } from './Diagrams';

const layers=[
  { name:'Personas y responsabilidad', tag:'QUIÉN RESPONDE', purpose:'Un catálogo relaciona cada proceso con su dueño, sus agentes y la persona supervisora.', example:'Compras → propuesta de pedido → agente comparador → técnico supervisor → responsable aprobador.', control:'Las identidades de los agentes son distintas de las personales. La persona responsable aprueba cambios en el alcance del proceso.' },
  { name:'Proceso y orquestación', tag:'QUÉ PASO TOCA', purpose:'El motor conserva el estado de cada expediente, coordina tareas, espera aprobaciones y gestiona excepciones.', example:'Un flujo de trabajo existente puede seguir sirviendo. Para ejecuciones de agentes con estado pueden evaluarse herramientas como LangGraph.', control:'Los reintentos tienen límite y no duplican operaciones. Se registran la versión del procedimiento, el resultado y la aprobación.' },
  { name:'Agentes y herramientas', tag:'QUÉ PUEDE HACER', purpose:'El agente recibe contexto y un conjunto de acciones permitidas. Los conectores realizan las operaciones sobre ERP, CRM o documentos.', example:'API para consultar stock; herramienta para crear un borrador; acción de envío separada y protegida. MCP puede estandarizar la conexión con herramientas y fuentes.', control:'El conector comprueba los permisos al ejecutar. Una instrucción del modelo no puede ampliar el acceso ni sustituir una autorización.' },
  { name:'Conocimiento y datos', tag:'EN QUÉ SE BASA', purpose:'Las aplicaciones siguen siendo la fuente de verdad. Un servicio recupera fragmentos relevantes de documentación vigente para cada expediente.', example:'Catálogo, procedimientos y contratos indexados con procedencia, versión y permisos. RAG significa recuperar información para incluirla en el contexto.', control:'La recuperación respeta el acceso del usuario y del proceso. El contenido de un documento se trata como dato, aunque incluya instrucciones dirigidas al agente.' },
  { name:'Modelos e inferencia', tag:'DÓNDE SE CALCULA', purpose:'El servicio de inferencia ejecuta el modelo seleccionado para cada tarea. Puede vivir en un servidor local, equipos distribuidos o un proveedor externo.', example:'Un motor local compatible, por ejemplo Ollama o LM Studio con PAIR; otra opción es un servicio de modelos gestionado por TI.', control:'El modelo debe caber en la memoria disponible. Se prueban calidad, latencia, concurrencia, consumo y licencias con la carga real.' },
  { name:'Operación y control', tag:'CÓMO SE MANTIENE', purpose:'Identidad, gestión de secretos, registros, evaluación y recuperación atraviesan todas las capas.', example:'Panel con expedientes pendientes, excepciones, coste por resultado, versiones y acciones aprobadas. Alertas y responsable de guardia según la criticidad.', control:'Separar pruebas y producción. Poder revocar una herramienta, pausar un proceso y volver a la versión anterior sin perder su trazabilidad.' },
];

export default function ArchitectureExplorer(){
  const [mode,setMode]=useState<Topology>('hybrid');const [layer,setLayer]=useState(0);const current=topologies[mode];
  return <>
    <section className="architecture-foundation"><p className="lab-label">Punto de partida</p><h2>Tu empresa ya tiene una base.</h2><div className="foundation-line"><span>Equipos y redes</span><b aria-hidden="true">+</b><span>ERP, CRM y aplicaciones</span><b aria-hidden="true">+</b><span>Documentos e identidad</span></div><p>Sobre esa base se incorpora un servicio de procesos y agentes. Los sistemas actuales conservan sus registros; las nuevas capacidades acceden a ellos mediante conexiones con permisos definidos.</p><p>Un agente es software. Varios agentes pueden compartir un modelo y un servidor. Crear un agente para Compras no exige comprar un equipo dedicado para Compras.</p></section>
    <section className="journey-section" aria-labelledby="topology-title"><p className="lab-label">01 / Arquitectura física y redes</p><h2 id="topology-title">Tres maneras de situar la inteligencia.</h2><p>Explora una topología. La elección depende de tus datos, la concurrencia, la conectividad y la capacidad de TI para operarla.</p>
      <div className="journey-toggle" role="group" aria-label="Topología de infraestructura">{(Object.keys(topologies) as Topology[]).map(id=><button key={id} onClick={()=>setMode(id)} aria-pressed={mode===id}>{topologies[id].label}</button>)}</div>
      <NetworkDiagram mode={mode}/>
      <div className="topology-explanation" aria-live="polite"><div><h3>{current.title}</h3><p>{current.text}</p></div><dl><div><dt>Cuándo considerarla</dt><dd>{current.fit}</dd></div><div><dt>Qué hay que resolver</dt><dd>{current.tradeoff}</dd></div></dl></div>
    </section>
    <section className="journey-section"><p className="lab-label">02 / Un ejemplo concreto: NVIDIA PAIR</p><h2>Repartir peticiones entre equipos.</h2>
      <div className="pair-layout"><div><p>Personal AI Router presenta un punto de acceso local para aplicaciones y agentes. Cada petición se dirige a un equipo compatible según el modelo disponible y la carga.</p><p>Se instala en el equipo de la aplicación; su entrada acepta solicitudes de ese mismo equipo. Los nodos que atienden peticiones necesitan un motor compatible, como Ollama o LM Studio, y el modelo correspondiente.</p><a className="text-link" href={references.pair.url} target="_blank" rel="noopener noreferrer">Ver la documentación de NVIDIA PAIR ↗</a></div>
        <div className="pair-routing" role="img" aria-label="Aplicación y PAIR local: la petición A se dirige al nodo RTX y la petición B al nodo DGX Spark."><div>Aplicación + PAIR local</div><svg viewBox="0 0 320 64" aria-hidden="true"><path d="M160 0V26H72V62 M160 26H248V62" fill="none" stroke="#74dfc4" strokeWidth="2"/><circle cx="72" cy="57" r="4" fill="#74dfc4"/><circle cx="248" cy="57" r="4" fill="#74dfc4"/></svg><div className="pair-nodes"><span>Petición A<br/><strong>Nodo RTX</strong></span><span>Petición B<br/><strong>DGX Spark</strong></span></div><small>Red local de confianza · solicitudes independientes</small></div>
      </div>
      <div className="architecture-note"><strong>PAIR no suma la memoria de las GPU.</strong><p>Una petición va a un sistema. Dividir un modelo entre nodos requiere otra arquitectura. NVIDIA documenta también la conexión de dos DGX Spark mediante QSFP a 200 GbE para cargas distribuidas; enlazarlos no hace que cualquier programa distribuya automáticamente su trabajo.</p><a href={references.cluster.url} target="_blank" rel="noopener noreferrer" className="text-link">Conexión de dos DGX Spark ↗</a></div>
      <details className="journey-disclosure"><summary>Qué valorar antes de elegir el hardware</summary><div><p>DGX Spark dispone de 128 GB de memoria unificada y combina CPU, GPU y red en un equipo compacto. Es una opción para desarrollo y cargas locales; la idoneidad de un despliegue depende del modelo y del servicio requerido.</p><p>Compara memoria útil, contexto, usuarios simultáneos, latencia, consumo eléctrico, refrigeración, soporte y recuperación. Un máximo teórico de parámetros o de operaciones no equivale a una capacidad garantizada de expedientes por hora.</p><a href={references.spark.url} className="text-link" target="_blank" rel="noopener noreferrer">Especificaciones de DGX Spark ↗</a></div></details>
    </section>
    <section className="journey-section" aria-labelledby="software-title"><p className="lab-label">03 / Arquitectura del software</p><h2 id="software-title">Seis capas para convertir<br/>capacidad en trabajo fiable.</h2><p>Selecciona una capa para ver su función, un ejemplo y el control que necesita. Es una arquitectura de referencia que debe adaptarse a cada empresa.</p>
      <div className="layer-explorer"><div className="layer-list" role="group" aria-label="Capas de software">{layers.map((l,i)=><button key={l.name} aria-pressed={layer===i} onClick={()=>setLayer(i)}><span>0{i+1}</span><span>{l.name}</span><span aria-hidden="true">↗</span></button>)}</div>
      <div className="layer-detail" aria-live="polite"><p className="lab-label">{layers[layer].tag}</p><h3>{layers[layer].name}</h3><p>{layers[layer].purpose}</p><h4>Cómo se concreta</h4><p>{layers[layer].example}</p><h4>Control necesario</h4><p>{layers[layer].control}</p></div></div>
      <p className="architecture-footnote">MCP facilita el intercambio con herramientas y fuentes; no es el motor del proceso ni sustituye el control de acceso. LangGraph es un ejemplo de ejecución con estado y revisión humana, no una elección obligatoria.</p>
    </section>
    <section className="journey-section"><p className="lab-label">04 / Cómo encajan proceso y tecnología</p><h2>Un expediente recorre toda la arquitectura.</h2><ol className="architecture-trace">{[
      ['Una persona registra una necesidad','El portal autentica al solicitante y crea un expediente con identificador único.'],
      ['El motor carga la definición aprobada','Compras ha definido agentes, supervisor, permisos y criterios de aceptación.'],
      ['El agente prepara una propuesta','Consulta fuentes autorizadas y utiliza el modelo local o externo permitido.'],
      ['La persona revisa y aprueba','Ve la propuesta, las fuentes y las excepciones; la aprobación queda ligada a esa versión.'],
      ['La integración ejecuta y registra','Comprueba la autorización, evita duplicados y conserva el resultado. El panel muestra el coste y las incidencias.'],
    ].map(([title,text],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><Link className="text-link" href="/empresa-nativa-ia/procesos">Explorar la ficha completa de un proceso →</Link></section>
    <section className="journey-section"><h2>Del sistema actual a la nueva operación.</h2><div className="journey-three"><article><h3>1. Conectar para leer</h3><p>Inventariar sistemas, clasificar datos, nombrar responsables y habilitar fuentes de solo lectura. Medir el proceso actual.</p></article><article><h3>2. Proponer y revisar</h3><p>Probar un proceso con casos representativos, registrar errores y medir el coste completo. Revisar cada salida.</p></article><article><h3>3. Ejecutar con límites</h3><p>Autorizar acciones concretas, configurar recuperación y comprobar el comportamiento ante fallos antes de extenderlo a otro departamento.</p></article></div><div className="architecture-note"><strong>Local se comprueba de extremo a extremo.</strong><p>Que el modelo se ejecute en tu oficina no impide que una herramienta envíe datos a un servicio externo. TI debe revisar también conectores, registros y salidas de red. Los servicios de procesos, bases de datos y colas pueden funcionar en servidores o máquinas virtuales existentes; la GPU se dimensiona para las tareas que realmente la requieren.</p></div></section>
  </>;
}
